# Generated by Django 5.2.7 on 2025-11-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_patient_user_doctor_patient_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefillLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pill_name', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('refill_needed', models.BooleanField(default=False)),
            ],
        ),
    ]
