# Generated by Django 5.2.7 on 2026-02-10 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_patient_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=10)),
                ('compartment', models.IntegerField()),
                ('frequency', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('status', models.CharField(default='Assigned', max_length=20)),
                ('last_taken', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='api.patient')),
            ],
        ),
    ]
