# Generated by Django 5.2.7 on 2026-05-21 09:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_medication'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medication',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='last_dispensed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='frequency',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Daily', max_length=50),
        ),
        migrations.AlterField(
            model_name='medication',
            name='status',
            field=models.CharField(choices=[('Assigned', 'Assigned'), ('Taken', 'Taken'), ('Missed', 'Missed')], default='Assigned', max_length=20),
        ),
        migrations.AlterField(
            model_name='medication',
            name='time',
            field=models.TimeField(),
        ),
        migrations.CreateModel(
            name='Dispense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pill_name', models.CharField(max_length=100)),
                ('compartment', models.IntegerField()),
                ('time_dispensed', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Dispensed', max_length=20)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispense_logs', to='api.medication')),
            ],
        ),
    ]
